import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";
import {Young_Serif, Outfit} from 'next/font/google'

const young_serif = Young_Serif({weight: "400", subsets:["latin"]});
const outfit = Outfit({weight:["400", "600","700"], subsets:["latin"]})

export const metadata: Metadata = {
  title: "Recipe page | by meni",
  description: "Generated by create next app",
   
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" type="image/png" sizes="32x32" href="./assets/images/favicon-32x32.png" />
        <title>Frontend Mentor | Your Page Title</title>
      </Head>
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
